file        = 1*record-eol

record-eol  = record ( 1*CR / EOF )       : Y1.

record      = field *comma-field          : [Y1|Y2].

comma-field = comma field                 : Y2.

field       = quoted / unquoted

quoted      = *WS dquote *(uqtext / comma) dquote *WS    : squeeze(Y3).

unquoted    = *uqtext                     : squeeze(Y).

uqtext      = unicodeish / 1*WS / doubledq

doubledq    = %x22 %x22                   : Y1.

dquote      = %x22

comma       = %x2C

unicodeish  = %x21 / %x23-2B / %x2D-7E / %x80-7FF / %x800-FFFF / %x10000-10FFFF
