file        = *record-eol

record-eol  = record eol                      : Y1.

eol         = CR / LF / CRLF

record      = field *comma-field              : [Y1|Y2].

comma-field = COMMA field                     : Y2.

field       = quoted / UQTEXTs

quoted      = *WS DQUOTE QTEXTs DQUOTE *WS    : Y3.

QTEXTs      = *QTEXT                          : merge(Y).

QTEXT       = UQTEXT / COMMA

UQTEXTs     = *UQTEXT                         : merge(Y).

UQTEXT      = UNICODEISH / WS / DOUBLEDQ

DOUBLEDQ    = DQUOTE DQUOTE                   : Y1.

CRLF        = CR LF

CR          = %x0A

LF          = %x0D

WS          = %x09 / %x20

DQUOTE      = %x22

COMMA       = %x2C

UNICODEISH  = %x21 / %x23-2B / %x2D-7E / %x80-7FF / %x800-FFFF / %x10000-10FFFF

