%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% prettyprinter

-module(fatpage_pp).

-export(
   [forms/2]).

-define(DBG(Form, E),
        try (E)
        catch C:R -> erlang:display({C, R, Form}),"\n :( \n"
        end).

forms(Forms, Filename) ->
    comment(Filename)++lists:flatmap(fun ppf/1, Forms).

ppf(Form) ->
    ?DBG(Form, erl_prettypr:format(Form, [{paper, 100}, {ribbon, 200}])++[10, 10]).

comment(Filename) ->
    flat("%%% This file was generated by fatpage from ~s.~n"
         "%%% It happened on ~s, at ~s. It was a ~s.~n"
         "%%% You should probably not modify it.~n~n",
         [Filename, fdate(), ftime(), fday()]).

fdate() ->
    {{Y, M, D}, _} = calendar:universal_time(),
    flat("~.4.0w-~.2.0w-~.2.0w", [Y, M, D]).

ftime() ->
    {_, {H, M, S}} = calendar:universal_time(),
    flat("~.2.0w:~.2.0w:~.2.0w", [H, M, S]).

fday() ->
    {{Y, M, D}, _} = calendar:universal_time(),
    case calendar:day_of_the_week(Y, M, D) of
        1 -> "Monday";
        2 -> "Tuesday";
        3 -> "Wednesday";
        4 -> "Thursday";
        5 -> "Friday";
        6 -> "Saturday";
        7 -> "Sunday"
    end.

flat(F, As) ->
    lists:flatten(io_lib:format(F, As)).
